services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      - S3_ACCESS_KEY=minio
      - S3_SECRET_KEY=minio123
      - S3_SERVICE_URL=http://s3:9000
      - S3_BUCKET_NAME=ical2s3grpc
      - S3_REGION=us-east-1
      - S3_USE_HTTPS=false
      - S3_FORCE_PATH_STYLE=true
    depends_on:
      s3:
        condition: service_healthy
      s3-init:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
  
  s3:
    image: quay.io/minio/minio:latest
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    ports:
      - 9000:9000
      - 9001:9001
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    command:
      - server
      - /data
      - --console-address
      - ":9001"

  s3-init:
    image: quay.io/minio/mc:latest
    entrypoint:
      - /bin/sh
      - -c
      - mc alias set minio http://s3:9000 minio minio123 && mc mb minio/ical2s3grpc || true
    depends_on:
      s3:
        condition: service_healthy
