version: "3"

tasks:
  up:
    cmds:
      - docker compose up -d --wait

  ci:
    cmds:
      - dotnet restore
      - dotnet build --no-restore
      - dotnet format ical2s3grpc.sln --verbosity diagnostic
      - dotnet test --no-build --verbosity normal 
